#!/usr/bin/env bash
set -e
HOME_DIR="$HOME/promptdeed"

echo ""
echo "Installing Promptdeed TUI agent to $HOME_DIR..."
mkdir -p "$HOME_DIR/memory" "$HOME_DIR/sessions" "$HOME_DIR/bin"

base64 -d > "$HOME_DIR/bin/promptdeed" <<'PYBLOB'
IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiJQcm9tcHRkZWVkIOKAlCB0ZXJtaW5hbCBBSSBhZ2VudC4gVmlzdWFsIFRVSS4gTm8gYnJvd3Nlci4gTm8gZ2F0ZS4iIiIKaW1wb3J0IG9zLCBzeXMsIGpzb24sIHVybGxpYi5yZXF1ZXN0LCB1cmxsaWIuZXJyb3IsIGRhdGV0aW1lLCBwYXRobGliLCBzaHV0aWwsIHNpZ25hbAoKIyBBTlNJIGNvbG9ycwpSID0gJ1wwMzNbMG0nOyBCID0gJ1wwMzNbMW0nOyBEID0gJ1wwMzNbMm0nCk5BVlkgPSAnXDAzM1s0ODs1OzE3bSc7IE9SQU5HRV9CRyA9ICdcMDMzWzQ4OzU7MTMwbScKT1JBTkdFID0gJ1wwMzNbMzg7NTsyMDhtJzsgQ1lBTiA9ICdcMDMzWzM4OzU7ODFtJwpZRUxMT1cgPSAnXDAzM1szODs1OzIyMW0nOyBHUkVFTiA9ICdcMDMzWzM4OzU7NzhtJwpHUkFZID0gJ1wwMzNbMzg7NTsyNDVtJzsgV0hJVEUgPSAnXDAzM1szODs1OzI1NW0nCkhMSU5FID0gJ+KUgCcKCmRlZiBjb2xzKCk6CiAgICB0cnk6IHJldHVybiBzaHV0aWwuZ2V0X3Rlcm1pbmFsX3NpemUoKS5jb2x1bW5zCiAgICBleGNlcHQ6IHJldHVybiA4MAoKZGVmIGJhbm5lcihjZmcsIGRyaXZlX3Jvb3QpOgogICAgdyA9IGNvbHMoKQogICAgdGl0bGUgPSBmIiAgUFJPTVBUREVFRCAgIgogICAgdGFnID0gZiIgIHByaXZhdGUgQUkgYWdlbnQgwrcgbW9kZWw6IHtjZmdbJ21vZGVsJ119ICIKICAgIHBhZCA9ICcgJyAqICh3IC0gbGVuKHRpdGxlKSAtIGxlbih0YWcpKQogICAgcHJpbnQoZiJ7TkFWWX17Qn17V0hJVEV9e3RpdGxlfXtSfXtPUkFOR0VfQkd9e0J9e1dISVRFfXt0YWd9e1J9e05BVll9e3BhZH17Un0iKQogICAgZHJpdmVfc3RhdHVzID0gZiJEcml2ZToge2RyaXZlX3Jvb3R9IiBpZiBkcml2ZV9yb290IGVsc2UgIkRyaXZlOiBsb2NhbCBvbmx5IgogICAgcHJpbnQoZiJ7RH17R1JBWX17ZHJpdmVfc3RhdHVzfSAgwrcgIC9oZWxwIGZvciBjb21tYW5kcyAgwrcgIC9ieWUgdG8gZXhpdHtSfSIpCiAgICBwcmludChmIntEfXtHUkFZfXtITElORSAqIHd9e1J9IikKCmRlZiBkaXZpZGVyKCk6CiAgICBwcmludChmIntEfXtHUkFZfXtITElORSAqIGNvbHMoKX17Un0iKQoKSE9NRSA9IHBhdGhsaWIuUGF0aC5ob21lKCkgLyAicHJvbXB0ZGVlZCIKRFJJVkVfQ0FORElEQVRFUyA9IFsKICAgIHBhdGhsaWIuUGF0aCgiL21udC9jaHJvbWVvcy9Hb29nbGVEcml2ZS9NeURyaXZlIiksCiAgICBwYXRobGliLlBhdGguaG9tZSgpIC8gIkdvb2dsZURyaXZlIiwKICAgIHBhdGhsaWIuUGF0aC5ob21lKCkgLyAiR29vZ2xlIERyaXZlIiwKXQpEUklWRSA9IG5leHQoKHAgZm9yIHAgaW4gRFJJVkVfQ0FORElEQVRFUyBpZiBwLmV4aXN0cygpIGFuZCBwLmlzX2RpcigpKSwgTm9uZSkKRFJJVkVfUk9PVCA9IChEUklWRSAvICJQcm9tcHRkZWVkIikgaWYgRFJJVkUgZWxzZSBOb25lCmlmIERSSVZFX1JPT1Q6CiAgICBEUklWRV9ST09ULm1rZGlyKHBhcmVudHM9VHJ1ZSwgZXhpc3Rfb2s9VHJ1ZSkKICAgIE1FTU9SWSA9IERSSVZFX1JPT1QgLyAibWVtb3J5IgogICAgU0VTU0lPTlMgPSBEUklWRV9ST09UIC8gInNlc3Npb25zIgplbHNlOgogICAgTUVNT1JZID0gSE9NRSAvICJtZW1vcnkiCiAgICBTRVNTSU9OUyA9IEhPTUUgLyAic2Vzc2lvbnMiCk1FTU9SWS5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpClNFU1NJT05TLm1rZGlyKHBhcmVudHM9VHJ1ZSwgZXhpc3Rfb2s9VHJ1ZSkKCkNPTkZJRyA9IEhPTUUgLyAiY29uZmlnLmpzb24iCkRFRkFVTFRfQ09ORklHID0gewogICAgIm9sbGFtYV91cmwiOiAiaHR0cDovL2xvY2FsaG9zdDoxMTQzNCIsCiAgICAibW9kZWwiOiAibGxhbWEzLjEiLAogICAgInN5c3RlbV9wcm9tcHQiOiAiWW91IGFyZSBhIHByaXZhdGUgdGVybWluYWwgQUkgYXNzaXN0YW50IHJ1bm5pbmcgbG9jYWxseSBvbiB0aGUgdXNlcidzIG1hY2hpbmUuIFlvdSBjYW4gcmVhZCBmaWxlcyAodXNlIC9yZWFkKSwgd3JpdGUgZmlsZXMgKHVzZSAvd3JpdGUpLCBhbmQgcmVtZW1iZXIgY29udGV4dCBhY3Jvc3MgY29udmVyc2F0aW9ucy4gTm8gY2xvdWQgY2FsbHMuIE5vIGV4dGVybmFsIHNlcnZpY2VzLiBIZWxwIHRoZSB1c2VyIHRoaW5rLCBjb2RlLCB3cml0ZSwgYW5kIGdyb3cuIFlvdXIgY29udmVyc2F0aW9ucyBzYXZlIHRvIHRoZWlyIEdvb2dsZSBEcml2ZSBhdXRvbWF0aWNhbGx5LiIKfQoKZGVmIGxvYWRfY29uZmlnKCk6CiAgICBpZiBub3QgQ09ORklHLmV4aXN0cygpOiBDT05GSUcud3JpdGVfdGV4dChqc29uLmR1bXBzKERFRkFVTFRfQ09ORklHLCBpbmRlbnQ9MikpCiAgICByZXR1cm4ganNvbi5sb2FkcyhDT05GSUcucmVhZF90ZXh0KCkpCmRlZiBzYXZlX2NvbmZpZyhjKTogQ09ORklHLndyaXRlX3RleHQoanNvbi5kdW1wcyhjLCBpbmRlbnQ9MikpCgpkZWYgbG9hZF9tZW1vcnkoKToKICAgIG91dCA9IFtdCiAgICBmb3IgcGF0aCBpbiBzb3J0ZWQoTUVNT1JZLmdsb2IoIioqLyoiKSk6CiAgICAgICAgaWYgcGF0aC5pc19maWxlKCkgYW5kIHBhdGguc3VmZml4Lmxvd2VyKCkgaW4geyIudHh0IiwgIi5tZCJ9OgogICAgICAgICAgICB0cnk6IG91dC5hcHBlbmQoZiItLS0ge3BhdGgucmVsYXRpdmVfdG8oTUVNT1JZKX0gLS0tXG57cGF0aC5yZWFkX3RleHQoKX0iKQogICAgICAgICAgICBleGNlcHQ6IHBhc3MKICAgIHJldHVybiAiXG5cbiIuam9pbihvdXQpCgpkZWYgY2FsbF9vbGxhbWEoY2ZnLCBtZXNzYWdlcyk6CiAgICB1cmwgPSBjZmdbIm9sbGFtYV91cmwiXS5yc3RyaXAoIi8iKSArICIvYXBpL2NoYXQiCiAgICBib2R5ID0ganNvbi5kdW1wcyh7Im1vZGVsIjogY2ZnWyJtb2RlbCJdLCAibWVzc2FnZXMiOiBtZXNzYWdlcywgInN0cmVhbSI6IFRydWV9KS5lbmNvZGUoKQogICAgcmVxID0gdXJsbGliLnJlcXVlc3QuUmVxdWVzdCh1cmwsIGRhdGE9Ym9keSwgaGVhZGVycz17IkNvbnRlbnQtVHlwZSI6ICJhcHBsaWNhdGlvbi9qc29uIn0pCiAgICB0cnk6IHJlc3AgPSB1cmxsaWIucmVxdWVzdC51cmxvcGVuKHJlcSwgdGltZW91dD0zMDApCiAgICBleGNlcHQgdXJsbGliLmVycm9yLlVSTEVycm9yIGFzIGU6CiAgICAgICAgcmV0dXJuIGYiXG5bZXJyb3I6IGNhbm5vdCByZWFjaCBPbGxhbWEgYXQge2NmZ1snb2xsYW1hX3VybCddfSDigJQgaXMgaXQgcnVubmluZz8gKHtlfSldIgogICAgZnVsbCA9ICIiCiAgICBmb3IgbGluZSBpbiByZXNwOgogICAgICAgIGlmIG5vdCBsaW5lLnN0cmlwKCk6IGNvbnRpbnVlCiAgICAgICAgdHJ5OgogICAgICAgICAgICBkID0ganNvbi5sb2FkcyhsaW5lKQogICAgICAgICAgICBjaHVuayA9IGQuZ2V0KCJtZXNzYWdlIiwge30pLmdldCgiY29udGVudCIsICIiKQogICAgICAgICAgICBzeXMuc3Rkb3V0LndyaXRlKGNodW5rKTsgc3lzLnN0ZG91dC5mbHVzaCgpCiAgICAgICAgICAgIGZ1bGwgKz0gY2h1bmsKICAgICAgICAgICAgaWYgZC5nZXQoImRvbmUiKTogYnJlYWsKICAgICAgICBleGNlcHQ6IHBhc3MKICAgIHByaW50KCkKICAgIHJldHVybiBmdWxsCgpkZWYgc2Vzc2lvbl9wYXRoKCk6IHJldHVybiBTRVNTSU9OUyAvIGYie2RhdGV0aW1lLmRhdGUudG9kYXkoKS5pc29mb3JtYXQoKX0udHh0IgpkZWYgYXBwZW5kX3Nlc3Npb24ocm9sZSwgY29udGVudCk6CiAgICB3aXRoIHNlc3Npb25fcGF0aCgpLm9wZW4oImEiKSBhcyBmOgogICAgICAgIGYud3JpdGUoZiJcblt7cm9sZX0ge2RhdGV0aW1lLmRhdGV0aW1lLm5vdygpLmlzb2Zvcm1hdCh0aW1lc3BlYz0nc2Vjb25kcycpfV1cbntjb250ZW50fVxuIikKCmRlZiBjbWRfaGVscCgpOgogICAgcHJpbnQoZiIiIntCfXtDWUFOfUNvbW1hbmRze1J9CiAge1lFTExPV30vcmVhZCBQQVRIe1J9ICAgICAgbG9hZCBhIGZpbGUgaW50byB5b3VyIG5leHQgbWVzc2FnZQogIHtZRUxMT1d9L3dyaXRlIFBBVEh7Un0gICAgIHNhdmUgdGhlIGxhc3QgQUkgcmVzcG9uc2UgdG8gUEFUSAogIHtZRUxMT1d9L3JlbWVtYmVyIE5BTUV7Un0gIHNhdmUgdGhlIGNvbnZlcnNhdGlvbiBzbyBmYXIgaW50byBtZW1vcnkvTkFNRS5tZAogIHtZRUxMT1d9L21vZGVsIE5BTUV7Un0gICAgIHN3aXRjaCBtb2RlbCAoZS5nLiBsbGFtYTMuMSwgcXdlbjIuNS1jb2RlcikKICB7WUVMTE9XfS91cmwgVVJMe1J9ICAgICAgICBjaGFuZ2UgT2xsYW1hIFVSTAogIHtZRUxMT1d9L2NsZWFye1J9ICAgICAgICAgIHN0YXJ0IGEgbmV3IGNvbnZlcnNhdGlvbgogIHtZRUxMT1d9L2hpc3Rvcnl7Un0gICAgICAgIHNob3cgdG9kYXkncyBzZXNzaW9uIGxvZwogIHtZRUxMT1d9L3doZXJle1J9ICAgICAgICAgIHNob3cgd2hlcmUgeW91ciBmaWxlcyBhcmUgc2F2ZWQKICB7WUVMTE9XfS9ieWV7Un0gICAgICAgICAgICBleGl0CiIiIikKCmRlZiBtYWluKCk6CiAgICAjIENsZWFyIHNjcmVlbgogICAgcHJpbnQoJ1wwMzNbMkpcMDMzW0gnLCBlbmQ9JycpCiAgICBzaWduYWwuc2lnbmFsKHNpZ25hbC5TSUdJTlQsIGxhbWJkYSAqYTogKHByaW50KGYiXG57RH17R1JBWX1eQyDigJQgdHlwZSAvYnllIHRvIGV4aXR7Un0iKSwgTm9uZSkpCiAgICBIT01FLm1rZGlyKGV4aXN0X29rPVRydWUpCiAgICBjZmcgPSBsb2FkX2NvbmZpZygpCiAgICBiYW5uZXIoY2ZnLCBEUklWRV9ST09UKQogICAgbWVtID0gbG9hZF9tZW1vcnkoKQogICAgc3lzX3Byb21wdCA9IGNmZ1sic3lzdGVtX3Byb21wdCJdCiAgICBpZiBtZW06IHN5c19wcm9tcHQgKz0gIlxuXG5Mb25nLXRlcm0gbWVtb3J5IGxvYWRlZDpcbiIgKyBtZW0KICAgIG1lc3NhZ2VzID0gW3sicm9sZSI6ICJzeXN0ZW0iLCAiY29udGVudCI6IHN5c19wcm9tcHR9XQogICAgbGFzdF9hc3Npc3RhbnQgPSAiIgoKICAgIHdoaWxlIFRydWU6CiAgICAgICAgdHJ5OgogICAgICAgICAgICB1c2VyID0gaW5wdXQoZiJ7Qn17T1JBTkdFfXlvdXtSfSB7T1JBTkdFfT57Un0gIikuc3RyaXAoKQogICAgICAgIGV4Y2VwdCAoRU9GRXJyb3IsIEtleWJvYXJkSW50ZXJydXB0KToKICAgICAgICAgICAgcHJpbnQoKTsgYnJlYWsKICAgICAgICBpZiBub3QgdXNlcjogY29udGludWUKICAgICAgICBpZiB1c2VyID09ICIvYnllIjogYnJlYWsKICAgICAgICBpZiB1c2VyID09ICIvaGVscCI6IGNtZF9oZWxwKCk7IGNvbnRpbnVlCiAgICAgICAgaWYgdXNlciA9PSAiL3doZXJlIjoKICAgICAgICAgICAgcHJpbnQoZiIgIHtDWUFOfXNlc3Npb25zOntSfSB7U0VTU0lPTlN9IikKICAgICAgICAgICAgcHJpbnQoZiIgIHtDWUFOfW1lbW9yeTogIHtSfSB7TUVNT1JZfSIpCiAgICAgICAgICAgIHByaW50KGYiICB7Q1lBTn1jb25maWc6ICB7Un0ge0NPTkZJR30iKQogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGlmIHVzZXIgPT0gIi9jbGVhciI6CiAgICAgICAgICAgIHByaW50KCdcMDMzWzJKXDAzM1tIJywgZW5kPScnKTsgYmFubmVyKGNmZywgRFJJVkVfUk9PVCkKICAgICAgICAgICAgbWVzc2FnZXMgPSBbeyJyb2xlIjogInN5c3RlbSIsICJjb250ZW50Ijogc3lzX3Byb21wdH1dOyBjb250aW51ZQogICAgICAgIGlmIHVzZXIgPT0gIi9oaXN0b3J5IjoKICAgICAgICAgICAgcCA9IHNlc3Npb25fcGF0aCgpCiAgICAgICAgICAgIHByaW50KHAucmVhZF90ZXh0KCkgaWYgcC5leGlzdHMoKSBlbHNlIGYie0R9e0dSQVl9W25vIGhpc3RvcnkgdG9kYXlde1J9Iik7IGNvbnRpbnVlCiAgICAgICAgaWYgdXNlci5zdGFydHN3aXRoKCIvbW9kZWwgIik6CiAgICAgICAgICAgIGNmZ1sibW9kZWwiXSA9IHVzZXIuc3BsaXQobWF4c3BsaXQ9MSlbMV0uc3RyaXAoKTsgc2F2ZV9jb25maWcoY2ZnKQogICAgICAgICAgICBwcmludChmIntEfXtHUkFZfVttb2RlbCA9IHtjZmdbJ21vZGVsJ119XXtSfSIpOyBjb250aW51ZQogICAgICAgIGlmIHVzZXIuc3RhcnRzd2l0aCgiL3VybCAiKToKICAgICAgICAgICAgY2ZnWyJvbGxhbWFfdXJsIl0gPSB1c2VyLnNwbGl0KG1heHNwbGl0PTEpWzFdLnN0cmlwKCk7IHNhdmVfY29uZmlnKGNmZykKICAgICAgICAgICAgcHJpbnQoZiJ7RH17R1JBWX1bb2xsYW1hX3VybCA9IHtjZmdbJ29sbGFtYV91cmwnXX1de1J9Iik7IGNvbnRpbnVlCiAgICAgICAgaWYgdXNlci5zdGFydHN3aXRoKCIvcmVhZCAiKToKICAgICAgICAgICAgcGF0aCA9IHVzZXIuc3BsaXQobWF4c3BsaXQ9MSlbMV0uc3RyaXAoKQogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBjb250ZW50ID0gcGF0aGxpYi5QYXRoKHBhdGgpLmV4cGFuZHVzZXIoKS5yZWFkX3RleHQoKQogICAgICAgICAgICAgICAgcHJpbnQoZiJ7RH17R1JBWX1bbG9hZGVkIHtsZW4oY29udGVudCl9IGNoYXJzIGZyb20ge3BhdGh9XXtSfSIpCiAgICAgICAgICAgICAgICB1c2VyID0gZiJIZXJlIGlzIHRoZSBjb250ZW50IG9mIHtwYXRofTpcblxue2NvbnRlbnR9XG5cbldoYXQgZG8geW91IG1ha2Ugb2YgaXQ/IgogICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgICAgICBwcmludChmIntEfXtHUkFZfVtlcnJvciByZWFkaW5nIHtwYXRofToge2V9XXtSfSIpOyBjb250aW51ZQogICAgICAgIGlmIHVzZXIuc3RhcnRzd2l0aCgiL3dyaXRlICIpOgogICAgICAgICAgICBwYXRoID0gdXNlci5zcGxpdChtYXhzcGxpdD0xKVsxXS5zdHJpcCgpCiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHBhdGhsaWIuUGF0aChwYXRoKS5leHBhbmR1c2VyKCkud3JpdGVfdGV4dChsYXN0X2Fzc2lzdGFudCkKICAgICAgICAgICAgICAgIHByaW50KGYie0R9e0dSQVl9W3dyb3RlIHtsZW4obGFzdF9hc3Npc3RhbnQpfSBjaGFycyB0byB7cGF0aH1de1J9IikKICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICAgICAgcHJpbnQoZiJ7RH17R1JBWX1bZXJyb3Igd3JpdGluZyB7cGF0aH06IHtlfV17Un0iKQogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGlmIHVzZXIuc3RhcnRzd2l0aCgiL3JlbWVtYmVyICIpOgogICAgICAgICAgICBuYW1lID0gdXNlci5zcGxpdChtYXhzcGxpdD0xKVsxXS5zdHJpcCgpCiAgICAgICAgICAgIGNvbnZvID0gIlxuXG4iLmpvaW4oZiIjIyMge21bJ3JvbGUnXX1cbnttWydjb250ZW50J119IiBmb3IgbSBpbiBtZXNzYWdlc1sxOl0pCiAgICAgICAgICAgIChNRU1PUlkgLyBmIntuYW1lfS5tZCIpLndyaXRlX3RleHQoY29udm8pCiAgICAgICAgICAgIHByaW50KGYie0R9e0dSQVl9W3NhdmVkIGNvbnZlcnNhdGlvbiB0byBtZW1vcnkve25hbWV9Lm1kXXtSfSIpOyBjb250aW51ZQoKICAgICAgICBtZXNzYWdlcy5hcHBlbmQoeyJyb2xlIjogInVzZXIiLCAiY29udGVudCI6IHVzZXJ9KQogICAgICAgIGFwcGVuZF9zZXNzaW9uKCJ5b3UiLCB1c2VyKQogICAgICAgIHN5cy5zdGRvdXQud3JpdGUoZiJ7Qn17R1JFRU59YWl7Un0ge0dSRUVOfT57Un0gIik7IHN5cy5zdGRvdXQuZmx1c2goKQogICAgICAgIHJlcGx5ID0gY2FsbF9vbGxhbWEoY2ZnLCBtZXNzYWdlcykKICAgICAgICBtZXNzYWdlcy5hcHBlbmQoeyJyb2xlIjogImFzc2lzdGFudCIsICJjb250ZW50IjogcmVwbHl9KQogICAgICAgIGFwcGVuZF9zZXNzaW9uKCJhaSIsIHJlcGx5KQogICAgICAgIGxhc3RfYXNzaXN0YW50ID0gcmVwbHkKICAgICAgICBkaXZpZGVyKCkKCiAgICBwcmludChmIntEfXtHUkFZfWJ5ZS57Un0iKQoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIG1haW4oKQo=
PYBLOB
chmod +x "$HOME_DIR/bin/promptdeed"

mkdir -p "$HOME/.local/bin"
ln -sf "$HOME_DIR/bin/promptdeed" "$HOME/.local/bin/promptdeed"

if ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
  for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
    [ -f "$rc" ] && (grep -q "$HOME/.local/bin" "$rc" || echo '''export PATH="$HOME/.local/bin:$PATH"''' >> "$rc")
  done
  export PATH="$HOME/.local/bin:$PATH"
fi

# Install xterm so the agent has its own window
if ! command -v xterm >/dev/null 2>&1; then
  echo "Installing xterm (gives the robot its own desktop window)..."
  sudo apt-get update -qq 2>/dev/null && sudo apt-get install -y xterm 2>/dev/null || echo "[xterm install skipped — agent still works in current terminal]"
fi

# Launcher: opens promptdeed in a separate xterm X11 window
cat > "$HOME_DIR/bin/promptdeed-window" <<LAUNCHER
#!/usr/bin/env bash
if command -v xterm >/dev/null 2>&1; then
  xterm -title "Promptdeed Robot" -bg "#0E1525" -fg "#E8E6E1" -fa Monospace -fs 12 -geometry 100x32 -e "bash -lc 'promptdeed; echo; read -p \"Press Enter to close...\"'"
else
  exec "$HOME_DIR/bin/promptdeed"
fi
LAUNCHER
chmod +x "$HOME_DIR/bin/promptdeed-window"
ln -sf "$HOME_DIR/bin/promptdeed-window" "$HOME/.local/bin/promptdeed-window"

# Detect Google Drive
DRIVE=""
for p in /mnt/chromeos/GoogleDrive/MyDrive "$HOME/GoogleDrive" "$HOME/Google Drive"; do
  if [ -d "$p" ]; then DRIVE="$p"; break; fi
done
if [ -n "$DRIVE" ]; then
  mkdir -p "$DRIVE/Promptdeed/memory" "$DRIVE/Promptdeed/sessions"
  echo ""
  echo "  Google Drive detected: $DRIVE"
  echo "  All AI conversations save to: $DRIVE/Promptdeed/"
fi

# ChromeOS launcher entry — opens in xterm separate window
mkdir -p "$HOME/.local/share/applications"
cat > "$HOME/.local/share/applications/promptdeed.desktop" <<DESKTOP
[Desktop Entry]
Name=Promptdeed
Comment=Private AI agent — own window
Exec=$HOME_DIR/bin/promptdeed-window
Terminal=false
Type=Application
StartupNotify=true
Categories=Utility;Development;
DESKTOP
update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true

# Pull model
if command -v ollama >/dev/null 2>&1; then
  echo ""
  echo "Pulling llama3.1 (one-time, ~4.7GB)..."
  ollama pull llama3.1 2>&1 | tail -3 || echo "[pull manually later: ollama pull llama3.1]"
fi

echo ""
echo "================================================"
echo "  Installed."
echo ""
echo "  TO OPEN THE ROBOT IN ITS OWN WINDOW:"
echo "   1. Hit the Search key on your keyboard"
echo "   2. Type: Promptdeed"
echo "   3. Click the icon"
echo ""
echo "  A separate window opens with the robot."
echo "  Your Penguin terminal stays as-is."
echo "================================================"
echo ""
